/*
 * This file was generated by the Gradle 'init' task.
 *
 * Copyright (c) 2025.  Jefferson Lab (JLab). All rights reserved. Permission
 * to use, copy, modify, and distribute  this software and its documentation for
 * educational, research, and not-for-profit purposes, without fee and without a
 * signed licensing agreement.
 *
 * IN NO EVENT SHALL JLAB BE LIABLE TO ANY PARTY FOR DIRECT, INDIRECT, SPECIAL
 * INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING LOST PROFITS, ARISING
 * OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF JLAB HAS
 * BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * JLAB SPECIFICALLY DISCLAIMS ANY WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE. THE CLARA SOFTWARE AND ACCOMPANYING DOCUMENTATION, IF ANY,
 * PROVIDED HEREUNDER IS PROVIDED "AS IS". JLAB HAS NO OBLIGATION TO PROVIDE
 * MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.
 *
 * This software was developed under the United States Government license.
 * For more information contact maintainer at jzarling@jlab.org
 * Department of Experimental Nuclear Physics, Jefferson Lab.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
}

group = "org.jlab.coda"
version = "2.1" // jev.version

java {
    toolchain { languageVersion.set(JavaLanguageVersion.of(8)) } // Modern gradle 9.1.x way of choosing JDK
    withJavadocJar()
}

repositories {
    mavenLocal()
    mavenCentral()
}

val coda: String? = System.getenv("CODA")
val prefix: String? = (findProperty("prefix") as String?) // pass with -Pprefix=/path

val srcDir = layout.projectDirectory.dir("java")
val docDir = layout.projectDirectory.dir("doc/javadoc")
val scriptsDir = layout.projectDirectory.dir("scripts")
val buildLib = layout.buildDirectory.dir("lib")

sourceSets {
    main {
        java.setSrcDirs(listOf("java"))
        resources {
            setSrcDirs(listOf("java"))
            include("**/*.properties", "**/*.png", "**/*.jpg", "**/*.gif", "**/*.xml")
            exclude("**/*.java")
        }
    }
}

// ---- Exclusive classpath resolution (CODA OR local) ----
dependencies {
    // CODA found: use ONLY $CODA/common/jar
    if (coda != null) {
        implementation(fileTree("$coda/common/jar") { include("*.jar") })
        println("[classpath] Using CODA common jars: $coda/common/jar")
    } 
    // CODA not found: use java/jars/java8
    else {
        implementation(fileTree("java/jars/java8") { include("*.jar") })
        println("[classpath] Using local jars: java/jars/java8")
    }

    testImplementation(platform("org.junit:junit-bom:5.10.3"))
    testImplementation("org.junit.jupiter:junit-jupiter")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

tasks.test { useJUnitPlatform() }

// Jar name/location + manifest
tasks.jar {
    archiveBaseName.set("JEventViewer")
    archiveVersion.set(project.version.toString())
    destinationDirectory.set(buildLib)
    // Import Ant manifest (carried over from using `ant` to build)
    val antManifest = srcDir.file("org/jlab/coda/eventViewer/manifest.mf").asFile
    if (antManifest.exists()) {
        manifest { from(antManifest) }
    }
}

tasks.register("env") {
    // Provide only primitives/strings as inputs
    inputs.property("srcDir", layout.projectDirectory.dir("java").asFile.absolutePath)
    inputs.property("buildDir", layout.buildDirectory.asFile.get().absolutePath)
    inputs.property("buildLib", layout.buildDirectory.dir("lib").get().asFile.absolutePath)
    inputs.property("docDir", layout.projectDirectory.dir("doc/javadoc").asFile.absolutePath)
    inputs.property("CODA", System.getenv("CODA") ?: "(unset)")
    inputs.property("prefix", (findProperty("prefix") as String?) ?: "(unset)")

    doLast {
        val p = inputs.properties
        println("Gradle environment:")
        println("  src.dir       = ${p["srcDir"]}")
        println("  build.dir     = ${p["buildDir"]}")
        println("  build.lib     = ${p["buildLib"]}")
        println("  doc.dir       = ${p["docDir"]}")
        println("  CODA          = ${p["CODA"]}")
        println("  prefix        = ${p["prefix"]}")
    }
}

// Javadoc (public)
tasks.javadoc {
    destinationDir = docDir.asFile
    (options as StandardJavadocDocletOptions).apply {
        memberLevel = JavadocMemberLevel.PUBLIC
        addBooleanOption("use", true)
    }
}

// Javadoc (developer / package)
tasks.register<Javadoc>("developdoc") {
    group = "documentation"
    description = "Create javadoc for developer (package access)."
    source = sourceSets.main.get().allJava
    classpath = sourceSets.main.get().compileClasspath
    destinationDir = docDir.asFile
    (options as StandardJavadocDocletOptions).apply {
        memberLevel = JavadocMemberLevel.PACKAGE
        addBooleanOption("use", true)
    }
}

// ---------- Install / Uninstall (mirrors Ant) ----------
val jarName = provider { tasks.jar.get().archiveFileName.get() }
val allJarNames = "JEventViewer-*.jar"

fun requireInstallDir() {
    if (prefix == null && coda == null) {
        throw GradleException("CODA env var not defined and -Pprefix not used, jar NOT installed")
    }
}

val installInPrefix = tasks.register("installInPrefix") {
    onlyIf { prefix != null }
    dependsOn(tasks.jar)
    doLast {
        val dest = file("$prefix/jar")
        dest.mkdirs()
        delete(fileTree(dest) { include(allJarNames) })
        copy { from(tasks.jar.get().archiveFile); into(dest) }
        println("Installed ${jarName.get()} into $dest")
    }
}

val installInCODA = tasks.register("installInCODA") {
    onlyIf { prefix == null && coda != null }
    dependsOn(tasks.jar)
    doLast {
        val dest = file("$coda/common/jar")
        dest.mkdirs()
        delete(fileTree(dest) { include(allJarNames) })
        copy { from(tasks.jar.get().archiveFile); into(dest) }
        println("Installed ${jarName.get()} into $dest")
    }
}

val installScriptsInPrefix = tasks.register<Copy>("installScriptsInPrefix") {
    onlyIf { prefix != null }
    from(scriptsDir)
    into(file("$prefix/bin"))
    include("*")
    filePermissions {
        // rwxr-xr-x (0755)
        user { read = true; write = true; execute = true }
        group { read = true; execute = true }
        other { read = true; execute = true }
    }
}

val installScriptsInCODA = tasks.register<Copy>("installScriptsInCODA") {
    onlyIf { prefix == null && coda != null }
    from(scriptsDir)
    into(file("$coda/common/bin"))
    include("*")
    filePermissions {
        // rwxr-xr-x (0755)
        user { read = true; write = true; execute = true }
        group { read = true; execute = true }
        other { read = true; execute = true }
    }
}

tasks.register("install") {
    group = "distribution"
    description = "Installs jar (and scripts) to prefix or CODA."
    dependsOn(tasks.jar)
    dependsOn(installInPrefix, installInCODA, installScriptsInPrefix, installScriptsInCODA)
    doFirst { requireInstallDir() }
}

val uninstallFromPrefix = tasks.register("uninstallFromPrefix") {
    onlyIf { prefix != null }
    doLast {
        delete(file("$prefix/jar/${jarName.get()}"))
        println("Removed ${jarName.get()} from $prefix/jar")
    }
}

val uninstallFromCODA = tasks.register("uninstallFromCODA") {
    onlyIf { prefix == null && coda != null }
    doLast {
        delete(file("$coda/common/jar/${jarName.get()}"))
        println("Removed ${jarName.get()} from $coda/common/jar")
    }
}

tasks.register("uninstall") {
    group = "distribution"
    description = "Uninstalls jar from prefix or CODA."
    dependsOn(uninstallFromPrefix, uninstallFromCODA)
    doFirst {
        if (prefix == null && coda == null) {
            throw GradleException("Installation directory not defined, jar NOT installed")
        }
    }
}

// Default task (Ant default=compile). Here we make `jar` the default.
defaultTasks("jar")
